"""The generator: committed files in, three kinds of static page out.

Never imports the store; deterministic by construction. See docs/DESIGN.md.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, PackageLoader, StrictUndefined
from markupsafe import Markup

from . import graph as graph_mod
from .corpus import Corpus, Name, Story, load_corpus
from .export import load_cast
from .render import format_date, format_partial, render_markdown
from .settings import load_settings

PACKAGE_ROOT = Path(__file__).parent
STATIC_ROOT = PACKAGE_ROOT / "static"

#: Written into the output root so a rebuild knows the directory is ours to clear.
#: Fixed content — anything varying would break byte-identical rebuilds.
BUILD_MARKER = ".sunday-build"
BUILD_MARKER_TEXT = "Generated by sunday. Safe to delete; rebuilt from committed files.\n"


class BuildError(Exception):
    """Raised when the build cannot safely proceed."""


@dataclass
class BuildResult:
    output_dir: Path
    page_count: int
    warnings: tuple[str, ...] = ()


# --------------------------------------------------------------------------- output


def prepare_output(output_dir: Path) -> None:
    """Clear the output tree so deleted or renamed stories leave no orphan.

    A non-empty directory with no build marker is refused rather than deleted.
    """
    output_dir = Path(output_dir)
    if output_dir.exists():
        if not output_dir.is_dir():
            raise BuildError(f"output path exists and is not a directory: {output_dir}")
        contents = list(output_dir.iterdir())
        if contents and not (output_dir / BUILD_MARKER).exists():
            raise BuildError(
                f"refusing to clear {output_dir}: it is not empty and was not generated "
                f"by sunday (no {BUILD_MARKER} marker). Choose a different --output, or "
                f"remove the directory yourself."
            )
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)
    (output_dir / BUILD_MARKER).write_text(BUILD_MARKER_TEXT, encoding="utf-8")


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


# ------------------------------------------------------------------------ rendering


def _environment() -> Environment:
    return Environment(
        loader=PackageLoader("sunday", "templates"),
        autoescape=True,
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


def _slugs_for(corpus: Corpus, story: Story, kind: str) -> str:
    """Space-separated name slugs for a story, used by the feed filter."""
    slugs = []
    for display in story.names_of_kind(kind):  # type: ignore[arg-type]
        name = corpus.name(kind, display)  # type: ignore[arg-type]
        if name is not None:
            slugs.append(name.slug)
    return " ".join(sorted(set(slugs)))


#: The feed's two orders: (key, sort-link label, path from the site root).
FEED_ORDERS = (
    ("published", "Newest first", ""),
    ("chronological", "Story chronology", "chronological/"),
)


def _feed_entry(corpus: Corpus, story: Story, when: str) -> dict[str, Any]:
    return {
        "story": story,
        "when": when,
        "character_slugs": _slugs_for(corpus, story, "character"),
        "location_slugs": _slugs_for(corpus, story, "location"),
    }


def _feed_sections(corpus: Corpus, order: str) -> list[dict[str, Any]]:
    """The feed's non-empty sections, each a heading (or None) and its entries."""
    if order == "published":
        sections = [
            (None, [_feed_entry(corpus, s, format_date(s.published)) for s in corpus.feed_order()])
        ]
    else:
        dated, undated = graph_mod.chronological_order(corpus)
        sections = [
            (None, [_feed_entry(corpus, s, format_partial(s.occurs)) for s in dated]),
            ("Undated", [_feed_entry(corpus, s, "—") for s in undated]),
        ]
    return [{"heading": h, "entries": entries} for h, entries in sections if entries]


# ---------------------------------------------------------------------------- build


def build_site(
    *,
    stories_dir: Path | str,
    settings_path: Path | str,
    cast_path: Path | str,
    output_dir: Path | str,
) -> BuildResult:
    """Generate the complete published site: feed (in each order), network, and story pages."""
    stories_dir = Path(stories_dir)
    output_dir = Path(output_dir)

    corpus = load_corpus(stories_dir)
    settings = load_settings(settings_path)
    cast = load_cast(cast_path)

    env = _environment()
    prepare_output(output_dir)

    published = corpus.published()
    pages = 0

    common = {"site_title": settings.title}

    # -- the feed, once per order ----------------------------------------------------
    feed_template = env.get_template("site/index.html")
    for order, _label, path in FEED_ORDERS:
        root = "../" * path.count("/")
        _write(
            output_dir / path / "index.html",
            feed_template.render(
                root=root,
                home=root or "./",
                order=order,
                orders=[
                    {"key": key, "label": label, "href": (root + p) or "./"}
                    for key, label, p in FEED_ORDERS
                ],
                sections=_feed_sections(corpus, order),
                **common,
            ),
        )
        pages += 1

    # -- one page per published story ---------------------------------------------
    story_template = env.get_template("site/story.html")
    for story in sorted(published, key=lambda s: s.slug):
        _write(
            output_dir / "stories" / story.slug / "index.html",
            story_template.render(
                root="../../",
                home="../../",
                story=story,
                body_html=Markup(render_markdown(story.body)),
                published_display=format_date(story.published),
                occurs_display=format_partial(story.occurs) if story.occurs else "",
                **common,
            ),
        )
        pages += 1

    # -- the network diagram, and the data behind it -------------------------------
    connection_graph = graph_mod.build_graph(corpus, cast)
    _write(
        output_dir / "graph.json",
        json.dumps(connection_graph.to_json(), indent=2, ensure_ascii=False, sort_keys=False)
        + "\n",
    )
    _write(
        output_dir / "network" / "index.html",
        env.get_template("site/network.html").render(
            root="../",
            home="../",
            node_count=len(connection_graph.nodes),
            edge_count=len(connection_graph.edges),
            **common,
        ),
    )
    pages += 1

    # -- static assets --------------------------------------------------------------
    for asset in ("site.css", "feed-filter.js", "network.js"):
        shutil.copyfile(STATIC_ROOT / asset, output_dir / asset)
    (output_dir / "vendor").mkdir(exist_ok=True)
    shutil.copyfile(
        STATIC_ROOT / "vendor" / "cytoscape.min.js", output_dir / "vendor" / "cytoscape.min.js"
    )

    return BuildResult(
        output_dir=output_dir,
        page_count=pages,
        warnings=_naming_warnings(corpus),
    )


def _naming_warnings(corpus: Corpus) -> tuple[str, ...]:
    """Naming findings, reported but never fatal. The build publishes regardless."""
    from .review import describe_finding, probable_duplicates

    return tuple(describe_finding(f) for f in probable_duplicates(corpus))
