"""The generator: committed files in, four kinds of static page out.

This module must never import `sunday.store`. The published site derives from
committed files alone (FR-007, Constitution II), which is what lets the build run
in CI where no store exists — and a test asserts the rule rather than trusting it.

Determinism is the other standing constraint (FR-016): every collection is sorted
before it is written, and nothing timestamped or randomly ordered reaches the
output. Two builds of unchanged sources produce byte-identical trees.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, PackageLoader, StrictUndefined
from markupsafe import Markup

from . import graph as graph_mod
from .corpus import Corpus, Name, Story, load_corpus
from .export import load_cast
from .render import format_date, format_partial, render_markdown
from .settings import load_settings

PACKAGE_ROOT = Path(__file__).parent
STATIC_ROOT = PACKAGE_ROOT / "static"

#: Written into the output root so a rebuild knows the directory is ours to clear.
#: Fixed content — anything varying would break byte-identical rebuilds.
BUILD_MARKER = ".sunday-build"
BUILD_MARKER_TEXT = "Generated by sunday. Safe to delete; rebuilt from committed files.\n"


class BuildError(Exception):
    """Raised when the build cannot safely proceed."""


@dataclass
class BuildResult:
    output_dir: Path
    page_count: int
    warnings: tuple[str, ...] = ()


# --------------------------------------------------------------------------- output


def prepare_output(output_dir: Path) -> None:
    """Clear the output tree so deleted or renamed stories leave no orphan (FR-018).

    Wipe-and-rebuild is the only approach that actually guarantees no stale page
    survives. Because `--output` is user-supplied, a directory that exists, is
    non-empty, and carries no build marker is refused rather than deleted — losing
    someone's unrelated files to a mistyped flag is not an acceptable failure mode.
    """
    output_dir = Path(output_dir)
    if output_dir.exists():
        if not output_dir.is_dir():
            raise BuildError(f"output path exists and is not a directory: {output_dir}")
        contents = list(output_dir.iterdir())
        if contents and not (output_dir / BUILD_MARKER).exists():
            raise BuildError(
                f"refusing to clear {output_dir}: it is not empty and was not generated "
                f"by sunday (no {BUILD_MARKER} marker). Choose a different --output, or "
                f"remove the directory yourself."
            )
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)
    (output_dir / BUILD_MARKER).write_text(BUILD_MARKER_TEXT, encoding="utf-8")


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


# ------------------------------------------------------------------------ rendering


def _environment() -> Environment:
    return Environment(
        loader=PackageLoader("sunday", "templates"),
        autoescape=True,
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


def _slugs_for(corpus: Corpus, story: Story, kind: str) -> str:
    """Space-separated name slugs for a story, used by the feed filter."""
    slugs = []
    for display in story.names_of_kind(kind):  # type: ignore[arg-type]
        name = corpus.name(kind, display)  # type: ignore[arg-type]
        if name is not None:
            slugs.append(name.slug)
    return " ".join(sorted(set(slugs)))


def _feed_items(corpus: Corpus) -> list[dict[str, Any]]:
    return [
        {
            "story": story,
            "published_display": format_date(story.published),
            "occurs_display": format_partial(story.occurs) if story.occurs else "",
            "character_slugs": _slugs_for(corpus, story, "character"),
            "location_slugs": _slugs_for(corpus, story, "location"),
        }
        for story in corpus.feed_order()
    ]


# ---------------------------------------------------------------------------- build


def build_site(
    *,
    stories_dir: Path | str,
    settings_path: Path | str,
    cast_path: Path | str,
    output_dir: Path | str,
) -> BuildResult:
    """Generate the complete published site.

    Emits exactly four kinds of page — feed, network, archive, story — and nothing
    else (FR-009a). No character, location, or tag pages: that material lives in the
    portal (FR-013).
    """
    stories_dir = Path(stories_dir)
    output_dir = Path(output_dir)

    corpus = load_corpus(stories_dir)
    settings = load_settings(settings_path)
    cast = load_cast(cast_path)

    env = _environment()
    prepare_output(output_dir)

    published = corpus.published()
    pages = 0

    common = {"site_title": settings.title}

    # -- the feed -----------------------------------------------------------------
    _write(
        output_dir / "index.html",
        env.get_template("site/index.html").render(
            root="", items=_feed_items(corpus), **common
        ),
    )
    pages += 1

    # -- one page per published story ---------------------------------------------
    story_template = env.get_template("site/story.html")
    for story in sorted(published, key=lambda s: s.slug):
        _write(
            output_dir / "stories" / story.slug / "index.html",
            story_template.render(
                root="../../",
                story=story,
                body_html=Markup(render_markdown(story.body)),
                published_display=format_date(story.published),
                occurs_display=format_partial(story.occurs) if story.occurs else "",
                **common,
            ),
        )
        pages += 1

    # -- the archive, in the fiction's own chronology ------------------------------
    dated, undated = graph_mod.archive_order(corpus)
    _write(
        output_dir / "archive" / "index.html",
        env.get_template("site/archive.html").render(
            root="../",
            dated=[
                {"story": s, "when": format_partial(s.occurs), "published_display": format_date(s.published)}
                for s in dated
            ],
            undated=[
                {"story": s, "published_display": format_date(s.published)} for s in undated
            ],
            **common,
        ),
    )
    pages += 1

    # -- the network diagram, and the data behind it -------------------------------
    connection_graph = graph_mod.build_graph(corpus, cast)
    _write(
        output_dir / "graph.json",
        json.dumps(connection_graph.to_json(), indent=2, ensure_ascii=False, sort_keys=False)
        + "\n",
    )
    _write(
        output_dir / "network" / "index.html",
        env.get_template("site/network.html").render(
            root="../",
            node_count=len(connection_graph.nodes),
            edge_count=len(connection_graph.edges),
            **common,
        ),
    )
    pages += 1

    # -- static assets --------------------------------------------------------------
    for asset in ("site.css", "feed-filter.js", "network.js"):
        shutil.copyfile(STATIC_ROOT / asset, output_dir / asset)
    (output_dir / "vendor").mkdir(exist_ok=True)
    shutil.copyfile(
        STATIC_ROOT / "vendor" / "cytoscape.min.js", output_dir / "vendor" / "cytoscape.min.js"
    )

    return BuildResult(
        output_dir=output_dir,
        page_count=pages,
        warnings=_naming_warnings(corpus),
    )


def _naming_warnings(corpus: Corpus) -> tuple[str, ...]:
    """Naming findings, reported but never fatal (FR-017a/b).

    Editorial judgment belongs in the portal, ahead of the build (FR-032c). The
    build repeats only the findings that suggest something is actually wrong —
    probable duplicates — and stays quiet about single-use and unprofiled names,
    which are ordinary states for a growing collection rather than mistakes.

    Whatever it finds, it publishes anyway.
    """
    from .review import describe_finding, probable_duplicates

    return tuple(describe_finding(f) for f in probable_duplicates(corpus))
