"""The `cast.yml` export — the store's outbound half of the boundary.

The generator cannot read the store (FR-007), and CI has no store at all, so
anything the published site needs must cross as a committed file. That is this
file, and it carries only what the diagram consumes: stated relationships and
display-name overrides (FR-038a).

Profile descriptions deliberately do *not* cross. Nothing published displays a
character biography, so exporting one would put private writing into a committed
file for no reader's benefit (FR-038b).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml

GENERATED_HEADER = """\
# GENERATED BY THE SUNDAY PORTAL — DO NOT EDIT.
# Relationships and display names are owned by the authoring store (.sunday/store.db).
# Hand edits will be overwritten on the next save; to change these, use the portal.
"""


class CastFileError(Exception):
    """Raised when `cast.yml` exists but cannot be understood."""


@dataclass(frozen=True)
class RelationshipEntry:
    """One stated connection, as it appears in the export."""

    from_name: str
    to_name: str
    description: str = ""
    directed: bool = False

    @property
    def sort_key(self) -> tuple[str, str, str]:
        return (self.from_name, self.to_name, self.description)


@dataclass
class CastExport:
    """Everything `cast.yml` carries. Empty is a perfectly valid state."""

    display_names: dict[str, str] = field(default_factory=dict)
    relationships: tuple[RelationshipEntry, ...] = ()

    def label_for(self, name: str) -> str:
        """The label the diagram should use for a name."""
        return self.display_names.get(name, name)


def load_cast(path: Path | str) -> CastExport:
    """Read `cast.yml`.

    A missing file is *not* an error — a collection with no profiles and no
    relationships is normal, and the diagram simply has no stated edges or label
    overrides (contracts/cli.md).
    """
    path = Path(path)
    if not path.exists():
        return CastExport()

    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise CastFileError(f"{path}: not valid YAML: {exc}") from exc

    if data is None:
        return CastExport()
    if not isinstance(data, dict):
        raise CastFileError(f"{path}: must be a mapping")

    display_names: dict[str, str] = {}
    for entry in data.get("display_names") or ():
        if not isinstance(entry, dict) or not entry.get("name"):
            raise CastFileError(f"{path}: each display_names entry needs a 'name'")
        override = entry.get("display_name")
        if override:
            display_names[str(entry["name"]).strip()] = str(override).strip()

    relationships: list[RelationshipEntry] = []
    for entry in data.get("relationships") or ():
        if not isinstance(entry, dict):
            raise CastFileError(f"{path}: each relationships entry must be a mapping")
        if not entry.get("from") or not entry.get("to"):
            raise CastFileError(f"{path}: each relationship needs 'from' and 'to'")
        relationships.append(
            RelationshipEntry(
                from_name=str(entry["from"]).strip(),
                to_name=str(entry["to"]).strip(),
                description=str(entry.get("description", "") or "").strip(),
                directed=bool(entry.get("directed", False)),
            )
        )

    return CastExport(
        display_names=display_names,
        relationships=tuple(sorted(relationships, key=lambda r: r.sort_key)),
    )


def dump_cast(export: CastExport) -> str:
    """Serialize a `CastExport` to the exact text of `cast.yml`.

    Sorted throughout, so the committed file has legible diffs and the build stays
    deterministic. Emits no `description` field for a profile — see FR-038b.
    """
    payload: dict[str, object] = {}

    if export.display_names:
        payload["display_names"] = [
            {"name": name, "display_name": export.display_names[name]}
            for name in sorted(export.display_names)
        ]

    if export.relationships:
        payload["relationships"] = [
            {
                "from": rel.from_name,
                "to": rel.to_name,
                "description": rel.description,
                "directed": rel.directed,
            }
            for rel in sorted(export.relationships, key=lambda r: r.sort_key)
        ]

    if not payload:
        return GENERATED_HEADER

    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return GENERATED_HEADER + "\n" + body


def write_cast(path: Path | str, export: CastExport) -> None:
    """Write `cast.yml`, creating parent directories as needed."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dump_cast(export), encoding="utf-8")


def export_from_store(store) -> CastExport:
    """Build the export from current store state.

    Carries display names and relationships only. A profile *description* is
    deliberately not included: nothing on the published site displays one, so
    exporting it would place private writing in a committed file for no reader
    (FR-038b).
    """
    display_names = {
        subject.name: subject.display_name
        for subject in store.subjects()
        if subject.display_name
    }

    relationships = tuple(
        RelationshipEntry(
            from_name=rel.from_subject.name,
            to_name=rel.to_subject.name,
            description=rel.description,
            directed=rel.directed,
        )
        for rel in store.relationships()
        if rel.from_subject is not None and rel.to_subject is not None
    )

    return CastExport(display_names=display_names, relationships=relationships)
